# Generated by Django 5.2.1 on 2025-06-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_travelpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('is_most_visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='image',
            field=models.ImageField(upload_to='travel_images/'),
        ),
    ]
