# Generated by Django 5.2.1 on 2025-06-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_customuser_passwordresetrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='is_most_visited',
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
