# Generated by Django 5.2.1 on 2025-06-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0006_remove_tour_is_most_visited_alter_tour_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='most_visited',
            field=models.BooleanField(default=False),
        ),
    ]
