# Generated by Django 5.0 on 2025-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0007_tour_most_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
