# Generated by Django 5.0 on 2025-06-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0008_booking_user'),
        ('Travel', '0008_customuser_otp'),
    ]

    operations = [
    ]
